src/ergw_config.erl
Add the missing configuration validation of the rcfbuf socket option.
=> validate rcvbuf socket option

src/ergw_config.erl, src/ggsn_gn_proxy.erl, src/gtp_path.erl, src/gtp_socket.erl, src/pgw_s5s8_proxy.erl, test/ergw_ggsn_test_lib.erl, test/ergw_pgw_test_lib.erl, test/ergw_test_lib.erl, test/ergw_test_lib.hrl, test/ggsn_SUITE.erl, test/ggsn_proxy_SUITE.erl, test/pgw_SUITE.erl, test/pgw_proxy_SUITE.erl
Most changes are just test case improvements to verify the fixes.
The two functional changes are:
* the proxy is now better on picking the right direction for forwarding a packet
* fix that a path restart with multiple active context would crash the path handler
=> proxy and path restart fixes

priv/static/specs/http_api_spec.yaml, src/http_api_handler.erl, test/ergw_http_api_SUITE.erl
From this moment, the `/api/v1/status` and `/api/v1/status/accept-new`
return the same fileds in the same view.
cc: @RoadRunnr @tlnd
=> map fields names for consistency

src/http_api_handler.erl
as we actually have POST requests without body and there is no
sense to send Content-Type header.
=> not need to specify Content-Type header during POST requests

README.md, priv/enit/ggsn/etc/enit/ergw/99-user.config, rebar.lock, test/ergw_http_api_SUITE.erl, test/ggsn_SUITE.erl, test/ggsn_proxy_SUITE.erl, test/pgw_SUITE.erl, test/pgw_proxy_SUITE.erl, tetrapak/dev.config
ergw_aaa_mock has always use a configuration parameter
`shared_secret`. With the new config validitioan in place in
ergw_aaa, the invalid secret parameter in many samples and
test will no longer work. Replace it with the proper setting.
=> update ergw_aaa and fix configuration for aaa_mock

METRICS.md, src/gtp_socket.erl
os:perf_counter/0 use the RTSC which is not stable on all CPU's
and is not guranteed to be in sync between multiple CPU sockets.
Erlangs monotonic_time should not have the same issues.
=> switch timing metrics to erlang:monotonic_time/0

METRICS.md, src/ergw_api.erl, src/ergw_http_api.erl, src/gtp_socket.erl, src/http_api_handler.erl, test/ergw_http_api_SUITE.erl
This is an alternative version of PR #37.
There are two main problems with that PR:
1. ergw_api should not implement data conversion and certainly nothing front end specific. The code in there is for Erlang internal API's only. Therefore move the encoding specific code into the API handler.
2. exometer:get_values/1 call find_values/1 and then get_value/1 on each one, doing a exometer_get_info/1 for each value again duplicates work that was done before in find_values/1. Instead, use find_values together with get_value and avoid the get_info.
Also, do the re:replace on the metric name only once. Regex are expensive, doing to each component in the name is wasteful.
=> Serve Prometheus metrics

include/ergw.hrl, src/ergw_proxy_lib.erl, src/ggsn_gn.erl, src/ggsn_gn_proxy.erl, src/gtp_path.erl, src/gtp_v1_c.erl, src/gtp_v2_c.erl, src/pgw_s5s8.erl, src/pgw_s5s8_proxy.erl, test/ergw_ggsn_test_lib.erl, test/ergw_pgw_test_lib.erl, test/ggsn_proxy_SUITE.erl, test/pgw_proxy_SUITE.erl
Refactor the proxy code to make the error reply handling fix simpler.
Replies with cause = "Context not found" are send with TEID of zero. The reply context selection logic could not deal with that and dropped the reply.
Test case and fix added.
=> refactor proxy code and fix error reply handling

rebar.lock, src/gtp_context.erl, src/gtp_path.erl, src/gtp_socket.erl
the GTP socket logic only needs to access the GTP message header, not
the content of the message element. Therefore, move the encoding and
decoding of the message elements into the processing thread.
This prevents failures from invalid message elements in the socket
handler process.
=> rework the socket logic to en/decode IEs in the message handler process

src/ggsn_gn.erl, src/ggsn_gn_proxy.erl, src/gtp_context.erl, src/pgw_s5s8.erl, src/pgw_s5s8_proxy.erl, test/ergw_ggsn_test_lib.erl, test/ergw_pgw_test_lib.erl, test/ergw_test_lib.erl, test/ergw_test_lib.hrl, test/ggsn_SUITE.erl, test/ggsn_proxy_SUITE.erl, test/pgw_SUITE.erl, test/pgw_proxy_SUITE.erl
We register the pending requests in the context registry. Unlike,
TEID's, IMSI's and so, these are transient events and need to be
remove once a request is finished. It doesn't mater if the request
was abort or completed, it was to be removed when processing it is
done.
Command have to clean up immediately, requests should wait for a
response to be finished.
=> ensure all pending requests are removed from the request table

src/gtp_path.erl, test/ggsn_SUITE.erl, test/ggsn_proxy_SUITE.erl, test/pgw_SUITE.erl, test/pgw_proxy_SUITE.erl
The gtp_path process keeps and internal counter. This counter was
not reset properly when a path_restart happends.
=> fix the GTP path context counter and all statistics that use it

README.md, rebar.lock, src/ergw_cache.erl, src/ggsn_gn.erl, src/ggsn_gn_proxy.erl, src/gtp_c_lib.erl, src/gtp_context.erl, src/gtp_context_reg.erl, src/gtp_socket.erl, src/gtp_v1_c.erl, src/gtp_v2_c.erl, src/pgw_s5s8.erl, src/pgw_s5s8_proxy.erl, test/ergw_ggsn_test_lib.erl, test/ergw_pgw_test_lib.erl, test/ergw_test_lib.erl, test/ergw_test_lib.hrl, test/ggsn_SUITE.erl, test/ggsn_proxy_SUITE.erl, test/pgw_SUITE.erl, test/pgw_proxy_SUITE.erl
this makes sure that:
* context are cleaned properly
* duplicate context registration are caught
* incoming new context terminated colliding, old contexts
=> rework context registration

include/ergw.hrl, src/ergw_proxy_lib.erl, src/ggsn_gn.erl, src/ggsn_gn_proxy.erl, src/gtp_context.erl, src/gtp_context_reg.erl, src/gtp_path.erl, src/gtp_socket.erl, src/gtp_v1_c.erl, src/gtp_v2_c.erl, src/pgw_s5s8.erl, src/pgw_s5s8_proxy.erl, test/ergw_ggsn_test_lib.erl, test/ergw_pgw_test_lib.erl, test/ergw_test_lib.erl, test/ergw_test_lib.hrl, test/ggsn_SUITE.erl, test/ggsn_proxy_SUITE.erl, test/pgw_SUITE.erl, test/pgw_proxy_SUITE.erl
The missing context tear down and the wrong context keys caused the system failure error returns.
This should fix them.
=> fix context tear down

src/gtp_socket.erl
The third element in the list of data was missed.
Now we change this to debug level and print message via
gtp_c_lib:fmt_gtp/1.
=> Fix error log about invalid response in gtp_socket

src/gtp_c_lib.erl
IEs can be in binary format when we do the following:
gtp_packet:decode(Data, #{ies => binary})
This change prevent crash for such case.
=> Fix fmt_ies/1 during pretty print of gtp message

rebar.config, rebar.lock
With `gen_socket-0.6.3` came support for Erlang-R20+. A few commits (but
"untagged" yet) support for compiling on Alpine-Linux was added - hence
commit 195a42700ba15b7ddc26a49865abcdaa627eba33 of `gen_socket`.
=> Upgrade `gen_socket` to work on Erlang-R20+

README.md
`ergw-gtp-c-node` is a good example how to run `ergw`
=> Get rid of enit mention from README

CONFIG.md, src/ergw_proxy_lib.erl, src/ggsn_gn_proxy.erl, src/pgw_s5s8_proxy.erl, test/config_SUITE.erl
Loadbalancing between multiple destionation GSN's is already
supported. Make it so that the default GSN can also be a list of
condidates.
=> make the fallback GGSN/PGW IP setting into a list of candidates

.travis.yml, CONFIG.md, METRICS.md, src/gtp_redirector.erl, src/gtp_socket.erl, test/ergw_http_api_SUITE.erl, test/ergw_test_lib.erl, test/ergw_test_lib.hrl, test/ggsn_SUITE.erl, test/ggsn_proxy_SUITE.erl, test/gtp_redirector_SUITE.erl, test/pgw_SUITE.erl, test/pgw_proxy_SUITE.erl
The redirection mode means that a GTP request will be transferred to a GTP backed with saving source IP and port. For the GTP backend, such request looks like it came from particular GTP client directly. 
There are some matching rules to making a decision, see the example of configuration:
```erlang
{rrx, [
{type,      'gtp-c'},
{ip,        {192, 168, 1, 100}},
{reuseaddr, true},
{redirector, [
{keep_alive_timeout, 60000},  % (ms) how often redirector socket will send echo_request to nodes to keep connection up
{retransmit_timeout, 10000},  % (ms) how long request will be memorized to use previously selected node
{lb_type,            random}, % how to select node from list of nodes. now only `random` is supported
{nodes, [
{node, [
{name, <<"gsn">>},           % name will be used to …
```
=> Add redirector mode for GTP socket

src/ergw_dns.erl, test/dns_SUITE.erl
Before we used `resolve` and expected that server returns answer with
all entries resolved recursively. This cant be try in all cases.
This commit reworks lookup mechanism to traverse entries manually.
=> Rework DNS resolver to traverse records manually

src/gtp_c_lib.erl, test/ergw_ggsn_test_lib.erl, test/ergw_pgw_test_lib.erl, test/ergw_test_lib.hrl, test/ggsn_SUITE.erl, test/pgw_SUITE.erl
Prevents nonstandard-labels like "a.b" from being a problem later on.
In general labels should not contain dots:
https://www.etsi.org/deliver/etsi_ts/123000_123099/123003/14.07.00_60/ts_123003v140700p.pdf#page=67
but sometimes they do.
=> Split APN label if there is a dot

src/ergw_cache.erl, src/gtp_redirector.erl, src/gtp_socket.erl
Calling ergw_cache:expire/1 outside of an timeout event will
start a new timer regardless of wether there is already one
running.
Also, there is really no need to invoke expire outside of an
timer event. The normal internal cleanup in enter/4 should be
sufficient and the timer events will handle the rest.
Change the expire API so that it can deals with the timers
properly.
=> fix cache expire logic

src/ergw.erl, src/gtp_context_sup.erl, src/gtp_dp_kmod.erl, src/gtp_path.erl, src/gtp_socket.erl
This is cherry-picked f1afabe2cbbcd0901a369b9c28637b916d793db8 from `feature/rf` to `stable/1.x`
=> adjust GC and hibernation for session processes

.travis.yml
Although the key ID not considered specially secret, some key scanners
warn about it. So lets remove it and use travis environment variables
instead.
The old key has also been disabled in AWS.
=> remove the AWS key id from .travis

src/gtp_c_lib.erl
Using a list of APN labels with one of them being the wildcard
label was never supported. The wildcard was always supposed to
be the bare '_' atom (without a list).
The return value from normalize_labels for '_' was broken anyway
because lists:flatmap/2 expects a list as return from the mapping
fun.
=> drop the special atom '_' from the permited APN labels

include/ergw.hrl, rebar.config, rebar.lock, src/ergw_gsn_lib.erl, src/ergw_pfcp.erl, src/ggsn_gn.erl, src/gtp_context.erl, src/pgw_s5s8.erl, src/saegw_s11.erl, test/ergw_test_sx_up.erl, test/ggsn_SUITE.erl, test/pgw_SUITE.erl, test/saegw_s11_SUITE.erl
Handle Validity-Timer in C-node. The timer is started after the CCA
is received (as defined in RFC 4006).
=> implement Validity-Timer and the matching Reporting-Reason for Gy

src/ergw_api.erl, src/ergw_http_api.erl, src/http_api_handler.erl, test/ergw_http_api_SUITE.erl, test/pgw_SUITE.erl
In order to drain a PGW from GTP contexts in batches of N, `gtp_context:delete_context/1` needs to be called N times.
This PR implements APIs for this behaviour:
* a public one via the REST-API:  DELETE /api/v1/contexts/<count>
* an ergw-internal one in `ergw_api:delete_contexts/1`
Technical note:  `delete_context` will send a `delete_bearer_request` to the SGW with `reactivation requested`.
=> API for deleting multiple GTP contexts

src/ggsn_gn.erl, src/gtp_context.erl, src/gtp_ip_pool.erl, src/pgw_s5s8.erl, src/saegw_s11.erl, src/vrf.erl, test/ggsn_SUITE.erl, test/pgw_SUITE.erl, test/saegw_s11_SUITE.erl
* release the IP in the terminate handler and make sure the context
always record allocated UE IPs.
* add exometer metrics
* add test cases
=> ensure context IP's are always released when the context terminates

src/http_api_handler.erl, test/ergw_http_api_SUITE.erl
8cf5938 introduced IP pool metrics. Upon accessing these metrics via the
Prometheus format, the following invalid metric name is created:
pool_<<"sgi">>_ipv4_10_0_0_1_free 262112
The invalid part `<<"sgi">>` is caused by http_api_handler:ioize/1. This
commit fixes the function to produce:
pool_sgi_ipv4_10_0_0_1_free 262112
In addition, pools for IPv6 addresses would create an invalid metric
name for Prometheus (see [1]). By converting the ":" to "_", this is
fixed as well.
[1]: https://prometheus.io/docs/concepts/data_model/#metric-names-and-labels
=> Fix metric name of IP pool in metrics

test/ergw_test_lib.erl, test/ergw_test_lib.hrl, test/ggsn_SUITE.erl, test/pgw_SUITE.erl, test/saegw_s11_SUITE.erl
Some counters depend on shutdown methods that can a few clock
cycles longer. Retry a match on a exometer value at most
10 times.
=> Fix validation of exometer counters in test suites

rebar.config
In 4f84f63, *entop* was bumped to 0.4.2. At the same time, it was also
added to a *relx*-release. After seeing massive leaks of memory in
instances deployed in a testlab, recon:bin_leak/1 points to *cecho* for
leaking binaries. The memory usage reported by the Erlang VM itself kept
stable, but the OS level memory usage grew and grew. This memory leaking
stopped completely as soon as `application:stop(cecho)` was called.
As a result, *entop* and its dependency *cecho* are removed from *ergw*
for the time being.
=> Fix memory regression

rebar.config, rebar.lock
Set the ergw_aaa dependency version to 3.1.0 for Gy CCR retry and rate limiting
=> Test gy ccr retry and rate limit

.gitlab-ci.yml, .travis.yml
This create more readable image tags for builds from travis-ci.
gitlab CI is using a wrong tag, but that seems to be a gitlab CI bug (https://gitlab.com/gitlab-org/gitlab-ce/issues/61007)
=> use `git describe` to get a more semver like, readable tag

src/ergw_gsn_lib.erl
The only reason not to send the deletion request is when
the UPF just failed.
=> make delete_sgi_session always delete the PFCP session

src/ergw_sx_socket.erl
The PFCP sequence number needs to wrap arround at 24bits. The encoding
will cut off any excessive bits, but the resulting shorter sequence
number in the request packet will no longer match the internal (expected)
sequence number.
This mean that the answer could net be matched with request, leading
to a break down of communication.
=> fix PFCP sequence number overflow handling

.travis.yml, src/ergw_gsn_lib.erl, src/ergw_sx_node.erl, src/ergw_sx_node_reg.erl, src/ggsn_gn.erl, src/gtp_proxy_ds.erl, src/pgw_s5s8.erl, src/saegw_s11.erl, src/tdf.erl, test/bench_SUITE.erl, test/ergw_http_api_SUITE.erl, test/ergw_test_lib.erl, test/ergw_test_lib.hrl, test/ergw_test_sx_up.erl, test/ggsn_SUITE.erl, test/ggsn_proxy_SUITE.erl, test/pgw_SUITE.erl, test/pgw_proxy_SUITE.erl, test/saegw_s11_SUITE.erl, test/tdf_SUITE.erl
The first A in AAA might overrule our IP pool selection either through the Framed-{IPv6}-Pool attribute or by assigning IPs itself. That new pool or IP might reside on a different UPF node.
This implements the UPF re-selection based on IP pools only. When IPs are assigned, the matching pools *has* to be supplied in Framed-{IPv6}-Pool.
=> reselect UPF after result of authorization

test/tdf_SUITE.erl
The timing in setup_upf is not stable on all environments to get
the expected results. Reorder the test setup to reliably catch
the message we are interested in.
=> CT: fix random failures in tdf_SUITE setup_upf case

src/ergw_config.erl, src/ergw_gsn_lib.erl, test/config_SUITE.erl, test/ergw_ggsn_test_lib.erl, test/ggsn_SUITE.erl
Using a hard code IPv6 interface of 1 for the UE is not always
desirable. Make it configurable, choices default (1), random,
a give value or sgsnemu.
The sgsnemu option uses the 64 bit IPv6 prefix as the interface id.
This is concession to the way that sgsnemu handles it IPv6 contest
lookup and should allow IPv6 only bearers with sgsnemu.
=> make the IPv6 UE interface id configurable

docker/Dockerfile
Usually, a process spawning subprocesses is responsible for cleaning
them up once they finish. This responsibility propagates down to PID 1.
When finished subprocesses ("childs") are not reaped, they become zombies
which are never vanish. Over time, they can starve the system. Erlang and
Elixir does not take care of spawned children on its own. Thus, any
"remote console" interaction with a running Erlang node will leave behind
a couple of zombies when PID 1 is not taking care of them.
Inside the container, Erlang / Elixir is usually run as PID 1.
This commit adds tini as the new PID 1 of the containers. As a result, all
child processes will be reaped properly.
=> add tini PID 1 to ercdf container

src/ergw_gsn_lib.erl, src/ggsn_gn.erl, src/ggsn_gn_proxy.erl, src/pgw_s5s8.erl, src/pgw_s5s8_proxy.erl, src/saegw_s11.erl
Running erGW as a dual stack GTP GSN is currently not supported. Only
single stack (either IPv4 or IPv6) is supported. R15.7 clarified how
advertising dual stack capabilities should be done and who to use
such advertisements (hand-over from one version to the other).
Adjust our handling to match the specification update.
=> unify GTP peer IP handling in v1 and v2 handlers

src/ggsn_gn.erl, src/pgw_s5s8.erl, src/saegw_s11.erl, test/ggsn_SUITE.erl, test/pgw_SUITE.erl, test/saegw_s11_SUITE.erl
AAA actionion like 'stop' need to go before Gx, Gy or Rf actions to
ensure proper sidereffect propagation.
=> ensure ergw_aaa invocation order

.gitlab-ci.yml, .travis.yml, docker/Dockerfile
- on Travis:
- use Xenial for OTP 21.3 checks
- briefly test ARM64
- on gitlab, upgrade to 22.2.8
=> update travis build matrix and gitlab builds

src/ergw.erl, src/ergw_gsn_lib.erl, src/ergw_node_selection.erl, src/ergw_proxy_lib.erl, src/ergw_sx_node.erl, src/ergw_sx_node_mngr.erl, src/ergw_sx_node_sup.erl, src/ggsn_gn.erl, src/ggsn_gn_proxy.erl, src/pgw_s5s8.erl, src/pgw_s5s8_proxy.erl, src/saegw_s11.erl, test/node_selection_SUITE.erl
A DNS server might return the A records a NAPTR rr points to in the
AR section or it might not. When the A record is not available, do
a DNS lookup as part of the connect procedure (GTP and PFCP sockets).
=> support late DNS A record lookup

src/ergw_gtp_c_socket.erl, src/gtp_path.erl, test/ggsn_SUITE.erl, test/ggsn_proxy_SUITE.erl, test/pgw_SUITE.erl, test/pgw_proxy_SUITE.erl
Handle Echo Requests timeout and kill all open context. Add tests.
This only a quick. The whole state behavior of the GTP path realy
wants a proper FSM implementation.
=> fix path failure detection

.gitlab-ci.yml, docker/Dockerfile
By using Erlang/OTP 23.0, the disfunctional "netdev" - config option becomes functional again, due to the upstream bugfix erlang/otp#2600.
In addition to use Erlang/OTP 23.0 as the runtime for the docker image,
this PR pins the used rebar3 version to a specific version. This provides less surprises upon build runs.
=> Feature: Switch to Erlang/OTP 23

.gitlab-ci.yml, docker/Dockerfile
Upstream released a new version of Erlang/OTP to address several issues,
see [1]. Among those are compiler fixes which could produce faulty code
and improvements in handling UDP (and SCTP) sockets. To avoid hunting
ghost issues fixed already upstream, this commit switches to the new
available OTP.
[1]: https://erlang.org/pipermail/erlang-announce/2020-May/000112.html
=> Switch to Erlang/OTP-23.0.1

.gitlab-ci.yml, .travis.yml, README.md, docker/Dockerfile, rebar.config
Now that 23.0 seems to be stable and in accordance with the version support statement,
drop support for everything before 22.3.
=> upgrade to OTP-23.0.2

.gitlab-ci.yml, .travis.yml, src/ergw.erl, src/ergw_api.erl, src/ergw_config.erl, src/ergw_proxy_lib.erl, src/ggsn_gn.erl, src/ggsn_gn_proxy.erl, src/gtp_path.erl, src/gtp_path_reg.erl, src/pgw_s5s8.erl, src/pgw_s5s8_proxy.erl, src/saegw_s11.erl, test/config_SUITE.erl, test/ergw_ggsn_test_lib.erl, test/ergw_pgw_test_lib.erl, test/ergw_test_lib.erl, test/ergw_test_lib.hrl, test/ergw_test_sx_up.erl, test/ggsn_proxy_SUITE.erl, test/pgw_SUITE.erl, test/pgw_proxy_SUITE.erl, test/proxy_lib_SUITE.erl
=> path monitoring exhancements

src/ergw_context.erl, src/ergw_gsn_lib.erl, src/ergw_gtp_c_socket.erl, src/ergw_node_selection.erl, src/ergw_sx_node.erl, src/ergw_sx_socket.erl, src/ggsn_gn.erl, src/ggsn_gn_proxy.erl, src/gtp_context.erl, src/pgw_s5s8.erl, src/pgw_s5s8_proxy.erl, src/saegw_s11.erl, src/tdf.erl
The abuse of those log levels traces back to lager times where
level where color coded and would highlight messages.
This was very useful during debugging, but the log levels lead
to confusion when those message show up in production.
=> demote many log output from info, error and warning to debug

METRICS.md, src/ergw_config.erl, src/ergw_gsn_lib.erl, src/ergw_inet.erl, src/ergw_ip_pool.erl, src/ergw_local_pool.erl, src/ergw_local_pool_reg.erl, src/ergw_local_pool_sup.erl, src/ergw_pfcp.erl, src/ergw_sup.erl, src/ggsn_gn.erl, src/gtp_context.erl, src/pgw_s5s8.erl, src/saegw_s11.erl, src/sbi_nbsf_handler.erl, src/tdf.erl, test/config_SUITE.erl, test/ergw_http_api_SUITE.erl, test/ggsn_SUITE.erl, test/pgw_SUITE.erl, test/saegw_s11_SUITE.erl
* allow IPv4 and IPv6 request to run in parallel
* keep all pool information in the allocated lease
* use stored information when releasing the IP later
=> rework IP pool to be asynchronous and reusable

priv/dev.config
Added comma to map of `logger` section in `dev.config` configuration
=> Fix dev.config

README.md, config/ergw-c-node.config, simulator/ergw_sim.erl, src/ergw.erl, src/ergw_config.erl, src/ergw_pfcp.erl, src/ergw_sup.erl, src/ergw_sx_node.erl, src/ergw_tei_mngr.erl, src/ggsn_gn_proxy.erl, src/gtp_context.erl, src/gtp_context_reg.erl, src/pgw_s5s8_proxy.erl, test/config_SUITE.erl, test/pgw_SUITE.erl
Implementation of TDD which allows to define the available prefix of Tunnel Endpoint IDs by configuration.
------------------
Implementation of `TEI` calculation was get from [experimental branch](https://github.com/travelping/ergw/blob/exp/stateless/src/ergw_tei_mngr.erl#L177-L188) what was implemented by @RoadRunnr
=> Configurable TEID-Ranges

rebar.lock, src/ergw_charging.erl, src/ggsn_gn.erl, src/pgw_s5s8.erl, src/saegw_s11.erl, test/ergw_ggsn_test_lib.erl, test/ergw_pgw_test_lib.erl, test/ergw_saegw_test_lib.erl, test/ggsn_SUITE.erl, test/pgw_SUITE.erl, test/saegw_s11_SUITE.erl
* fix generation of GTP Change Report IEs
* band-aid fix for not querying URRs when there is event to report
=> fix URR processing and change reporting

src/gtp_path.erl, test/ggsn_proxy_SUITE.erl, test/pgw_proxy_SUITE.erl
Only down/busy/idle changes should change the echo timeout.
=> make sure a added/remove peer does not reset the echo interval

rebar.config
847e514 switched the Erlang runtime to OTP23. Both *recon* and
*observer_cli* support OTP23 in their latest releases (mostly for "alloc
compat").
This commit bumps both dependencies.
=> Update *recon* and *observer_cli* to support OTP23

include/ergw.hrl, rebar.config, rebar.lock, src/ergw_gsn_lib.erl, src/ergw_gtp_gsn_lib.erl, src/ergw_inet.erl, src/ergw_pfcp.erl, src/ergw_pfcp_context.erl, src/ergw_sx_node.erl, src/ggsn_gn.erl, src/ggsn_gn_proxy.erl, src/gtp_context.erl, src/pgw_s5s8.erl, src/pgw_s5s8_proxy.erl, src/saegw_s11.erl, src/sbi_nbsf_handler.erl, src/tdf.erl, test/ergw_test_sx_up.erl, test/ggsn_proxy_SUITE.erl, test/pgw_SUITE.erl, test/pgw_proxy_SUITE.erl
3GPP Rel. 16 removed the option to assign UP TEIDs in the CP instance. TEID assignment in the UPF is mandatory now.
This implements the CP part of that change.
=> implement UP based TEID assignment

src/ergw_gsn_lib.erl, src/ergw_sx_node.erl, test/ergw_test_sx_up.erl
When 3GPP Rel. 16 made UPF base TEID assignment mandatory, it also removed
the User Plane IP Resource Information IE. We still relied on that IE
for choosing the IP address type for TEID assignment.
Change that to choose bearer IP types based on the tunnel IP type.
Adjust test cases accordingly.
=> remove reliance on User Plane IP Resource Information IE

src/ergw_gtp_c_socket.erl, src/ggsn_gn.erl, src/ggsn_gn_proxy.erl, src/gtp_api.erl, src/gtp_context.erl, src/pgw_s5s8.erl, src/pgw_s5s8_proxy.erl, src/saegw_s11.erl, test/ergw_test_lib.erl, test/ergw_test_lib.hrl, test/ggsn_proxy_SUITE.erl, test/pgw_proxy_SUITE.erl
A unresponsive GGSN/PGW would leave the session context in proxy
mode dangling. More over, the proxy TEID would be zero and follow
up context teardown would send out a delete request with TEID = 0.
Handle the timeout and use an state timeout to handle the case where
the first request timed out, but a resent was successful.
Add a CT case.
=> handle timeouts create session/pdp_context requests

README.md, doc/walkthrough-saegw.config, doc/walkthrough-saegw.md
Issue https://github.com/travelping/ergw/issues/245.
Providing correct config example for `walkthrough-saegw.config` and for `configuration format`.
=> Fix issue #245: provided correct config example of sockets section

priv/dev-sx.config, priv/dev.config, simulator/ergw_sim.erl
Remove `sx_socket` option because `sx` socket is now handled in the sockets section of `ergw`
=> Remove sx_socket option

src/ergw_sx_node.erl
Issue https://github.com/travelping/ergw/issues/133
From the example of task, it can be seen that sometimes, for some reason, the addresses can have binary format like `<<10,65533,126,65533>>` etc. which can break the display of the address and will displayed something like `<<"\ný~ý">>` etc.
=> Fix issue #133 for correct display of IPv4 and IPv6

src/ergw_proxy_lib.erl, test/proxy_lib_SUITE.erl
Related to https://github.com/travelping/ergw/pull/268. Added missing test case in `proxy_lib_SUITE` and updated configuration for correct checking of `ergw_proxy_lib:choose_gw/4` function.
=> Add miss test case of proxy_lib_SUITE

src/ergw_gtp_c_socket.erl
A select info is generated whenever there is something to read from
the socket, in C terms `(POLLIN | POLLERR)`. There is no distinction
whether that is normal read or errqueue read (POLLERR).
This adds a heuristic to read the errqueue should we get no data from
a normal socket read.
=> fix reading from socket error queue

include/ergw.hrl, src/ergw_gtp_c_socket.erl, src/ergw_gtp_socket.erl, src/ergw_gtp_u_socket.erl, src/ergw_proxy_lib.erl, src/ergw_sx_node.erl, src/ggsn_gn.erl, src/ggsn_gn_proxy.erl, src/gtp_context.erl, src/gtp_path.erl, src/pgw_s5s8.erl, src/pgw_s5s8_proxy.erl, src/saegw_s11.erl, test/ergw_ggsn_test_lib.erl, test/ergw_pgw_test_lib.erl, test/ggsn_SUITE.erl, test/ggsn_proxy_SUITE.erl, test/pgw_SUITE.erl, test/pgw_proxy_SUITE.erl, test/saegw_s11_SUITE.erl
Both GTP v1 and v2 have similar definitions for UDP source port
of GTP requests:
> The UDP Source Port is a locally allocated port number at the sending GSN/RNC.
Doing so has advantages when the receiver is using RSSI, NAT gateways
need to map those requests and are helpful for outgoing proxies.
=> use random udp source port for GTP-C requests

test/ggsn_SUITE.erl, test/pgw_SUITE.erl, test/saegw_s11_SUITE.erl
This makes the group hierarchy on the non proxy cases match the
proxy tests. It has ipv4 and ipv6 as root groups and nested
groups underneath.
Especially the PGW suite benefits from that. Selecting to run the
common IPv4 test suite was not successfull with the old ordering.
With the new setup `rebar3 ct .. --group=ipv4,common` works.
=> CT: change the nested groups in the GTP suites

include/ergw.hrl, src/ergw.erl, src/ergw_api.erl, src/ergw_context.erl, src/ergw_gtp_socket.erl, src/ergw_pfcp.erl, src/ergw_pfcp_context.erl, src/ergw_sx_node.erl, src/gtp_context.erl, src/gtp_context_reg.erl, src/gtp_v1_c.erl, src/gtp_v2_c.erl, test/ergw_test_lib.erl, test/ergw_test_sx_up.erl, test/ggsn_SUITE.erl, test/ggsn_proxy_SUITE.erl, test/pgw_SUITE.erl, test/pgw_proxy_SUITE.erl, test/saegw_s11_SUITE.erl, test/tdf_SUITE.erl
Instead of having to count fields in tuples, records allow us to
specify matches with the more readable record syntax.
They also give us `tagged keys`, that means we can deduce the type
of the key from the record tag.
This was originally part of the stateless work, but will also be
helpful for the cluster registry.
=> replace context key tupels with records

src/ergw_pfcp_context.erl, test/ggsn_SUITE.erl, test/pgw_SUITE.erl, test/saegw_s11_SUITE.erl, test/tdf_SUITE.erl
Linking of online charging URRs in the has the side effect of triggering online charging updates in the offline charging periods instead of considering previously granted volume/time. This PR removes the linking of online URRs as a workaround.
=> Fix online charging URR link

METRICS.md
=> Add missing decription of PFCP metrics

src/ergw_gtp_c_socket.erl, src/ergw_gtp_socket.erl, test/config_SUITE.erl, test/pgw_SUITE.erl
The option can now be used to either select a random port (true or 0),
not seperate port (false) or a specific port (1024-65535) for sending
=> change socket config split_sockets to send_port

src/ergw.erl, src/ergw_app.erl, src/ergw_config.erl, src/ergw_sup.erl, test/gtp_proxy_ds_SUITE.erl
Our configuration loading and checking always had problems
with when to load and apply what. This reshuffle the part
to separate configuration validation and the actual application
of the handler and socket config.
=> Shuffle the config loading to make it available earlier

src/gtp_context.erl, src/gtp_v1_c.erl, test/ergw_ggsn_test_lib.erl, test/ergw_pgw_test_lib.erl, test/ergw_saegw_test_lib.erl, test/ggsn_SUITE.erl, test/ggsn_proxy_SUITE.erl, test/pgw_SUITE.erl, test/pgw_proxy_SUITE.erl, test/saegw_s11_SUITE.erl
Make sure to return a proper TEID when rejecting new sessions due to an internal block (accept_new == false).
Fixes #322
=> return proper sender TEID when rejecting new sessions

src/pgw_s5s8.erl
The hardcoded response could lead to unexpected changes in the QoS
settings. Instead rebuild the QoS AVP from the session values.
=> use Bearer QoS from session in Create Session Response

src/ergw_sx_socket.erl
This is quick fix for SEID duplication. A more comprehensive fix would combine the SEID generation and the registry, checking every SEID for a collision.
=> switch to rand:uniform/1 for SEID generation

src/pgw_s5s8_proxy.erl
The corruption of the statem data only happens when trying to close
the context. This was the cause for many of the CI failures in
pgw_proxy_SUITE.dns_node_selection.
While this might ocure in running instance as well, there should be
not operational impact as it only abort a context that is already
terminating.
=> fix statem data corruption in S5/S8 proxy

docker/Dockerfile
The https://github.com/erlang/docker-erlang-otp/blob/master/23/alpine/Dockerfile#L1 has base image what based upon `alpine:3.13`.
**Notes:**
`alpine:3.13` is based on `musl 1.2.x`. https://musl.libc.org/releases.html:
> musl-1.2.1.tar.gz (sig) - August 4, 2020
This release features the new "mallocng" malloc implementation, replacing musl's original dlmalloc-like allocator that suffered from fundamental design problems. Its major user-facing new properties are the ability to return freed memory on a much finer granularity and avoidance of many catastrophic fragmentation patterns. In addition it provides strong hardening against memory usage errors by the caller, including detection of overflows, double-free, and use-after-free, and does not admit corruption of allocator state via these …
=> Update alpine to 3.13 for Dockerfile

README.md
In https://github.com/travelping/ergw/pull/288 the Travis was replaced to GitHub Actions and not used anymore.
=> Remove Travis from README

.github/workflows/main.yml, .gitlab-ci.yml, docker/Dockerfile
The `SCTP` fix was included into `OTP 23.3.4` release:
https://github.com/erlang/otp/pull/4775 -> https://github.com/erlang/otp/commit/1cf647698614382f14d896a96a626910ca56ffed -> https://github.com/erlang/docker-erlang-otp/pull/342 -> https://github.com/docker-library/official-images/pull/10145 -> https://github.com/travelping/docker-erlang-otp/commit/95c923684138533579ff8c9978140213c08e8ccb. Based on `alpine:3.13` -> `linux-headers=5.4.5-r1`
=> Start use image 'quay.io/travelping/alpine-erlang:23.3.4'

apps/ergw_core/src/ergw_node_selection.erl, apps/ergw_core/test/node_selection_SUITE.erl
The 3GPP specification do not spell it out but seem to assume that
APN names are used in all places as case insensitive.
Lowercase all APN names from GTP before using it further.
=> lowercase APN before further processing it

apps/ergw_core/src/ergw_gtp_gsn_lib.erl, apps/ergw_core/src/gtp_context.erl, apps/ergw_core/test/ergw_test_sx_up.erl, apps/ergw_core/test/pgw_SUITE.erl
Support `PFCP Session Deleted By the UP function` procedure that is part
of the EPFAR (Enhanced PFCP Association Release) feature.
The actually release procedure is not supported, but the "Deleted By the UPF"
can already be used to signal session deletion in the UPF
=> add PSDBU part or the EPFAR feature

apps/ergw_core/c_src/Makefile, apps/ergw_core/c_src/uint32_fy_shuffle.c, apps/ergw_core/rebar.config, apps/ergw_core/src/ergw_local_pool.erl, apps/ergw_core/src/ergw_local_pool_reg.erl, apps/ergw_core/src/uint32_fy_shuffle.erl
Initialized the free IP pool with a random order and time stamp to build a queue in the ets table. Released IPs are appended to the end of the free queue (through the timestamp).
=> new IP assignment, random init, fifo reuse of IP

apps/ergw/priv/schemas/ergw_config.yaml, apps/ergw/src/ergw_config.erl, apps/ergw/test/ergw_http_api_SUITE_data/ggsn.json, apps/ergw/test/sbi_nbsf_SUITE_data/ipv4.json, apps/ergw/test/sbi_nbsf_SUITE_data/ipv6.json, apps/ergw/test/smc_SUITE_data/ggsn.json, apps/ergw/test/smc_SUITE_data/ggsn_proxy.json, apps/ergw/test/smc_SUITE_data/pgw.json, apps/ergw/test/smc_SUITE_data/pgw_proxy.json, apps/ergw/test/smc_SUITE_data/saegw_s11.json, apps/ergw/test/smc_SUITE_data/tdf.json
The VRF name is similar to IpAddress as it can contain different
typed values. Instead of using type attribute to overload the
meaning of the name attribute, use per type properties.
=> align VRF name config format IpAddress

apps/ergw_core/src/ergw_gsn_lib.erl, apps/ergw_core/src/ergw_pfcp_context.erl, apps/ergw_core/src/tdf.erl, apps/ergw_core/test/ergw_pgw_test_lib.erl, apps/ergw_core/test/ergw_test_sx_up.erl, apps/ergw_core/test/pgw_SUITE.erl, apps/ergw_core/test/tdf_SUITE.erl
* rewrite UPF selection and reselection
* enhance VRF selecting in TDF mode to consider NAT pools
=> enhance VRF and node selection

apps/ergw/priv/schemas/ergw_config.yaml, apps/ergw/src/ergw_config.erl, apps/ergw/test/ergw_http_api_SUITE_data/ggsn.json, apps/ergw/test/sbi_nbsf_SUITE_data/ipv4.json, apps/ergw/test/sbi_nbsf_SUITE_data/ipv6.json, apps/ergw/test/smc_SUITE_data/ggsn.json, apps/ergw/test/smc_SUITE_data/ggsn_proxy.json, apps/ergw/test/smc_SUITE_data/pgw.json, apps/ergw/test/smc_SUITE_data/pgw_proxy.json, apps/ergw/test/smc_SUITE_data/saegw_s11.json, apps/ergw/test/smc_SUITE_data/tdf.json, apps/ergw_core/include/ergw.hrl, apps/ergw_core/src/ergw_apn.erl, apps/ergw_core/src/ergw_gtp_gsn_lib.erl, apps/ergw_core/src/ergw_pfcp_context.erl, apps/ergw_core/src/ggsn_gn.erl, apps/ergw_core/src/pgw_s5s8.erl, apps/ergw_core/src/saegw_s11.erl, apps/ergw_core/test/ergw_ggsn_test_lib.erl, apps/ergw_core/test/ggsn_SUITE.erl, apps/ergw_core/test/pgw_SUITE.erl, apps/ergw_core/test/pgw_dist_SUITE.erl, apps/ergw_core/test/saegw_s11_SUITE.erl
Decouple the Idle-Timeout from the GTP context inactivity timeout.
Idle-Timeout is now only used for decting periods of no traffic.
Inactivity timeout is a regular check from the CP to UP to check
if the PFCP context still exists.
=> rework context inactivity timeout

apps/ergw_core/src/gtp_context_reg.erl
The processing of registrations is moved from the single process registration server into the caller. This means that a registration does no longer block while waiting for an overloaded registry server to catch up.
=> non-blocking context registry

apps/ergw/src/ergw_compat.erl
* correct `dns` option in node_selection
* correct options in AAA service config
=> update config compat handler

apps/ergw_core/src/ergw_pfcp_context.erl
If an upf node pool is configured with only 1 IP version support, the value `undefined` was put into the session for the unsupported pool, causing problems when encoding AAA requests.
=> Only put valid pools in session

apps/ergw_cluster/src/ergw_cluster.erl
At startup of ergw_cluster process it creates a special process to
be sure that Erlang runtime fully started before ergw_cluster may
start to do its job. After that the special process done with its
job we terminate it with exit(ok) and this event is reported to log:
```
2021-08-15T23:11:03.058973+06:00 <0.1050.0> error: crasher: initial call: ergw_cluster:'-fun.startup/0-'/0, pid: <0.1050.0>, 
registered_name: [], exit: {ok,[{ergw_cluster,startup,0,[{file,"/home/alex/work/ergw/apps/ergw_cluster/src/ergw_cluster.erl"},
{line,170}]},{proc_lib,init_p,3,[{file,"proc_lib.erl"},{line,211}]}]}, ancestors: [ergw_cluster,ergw_cluster_sup,<0.1047.0>], 
message_queue_len: 0, messages: [], links: [<0.1049.0>], dictionary: [], trap_exit: false, status: running, heap_size: 376, 
stack_size: 29, …
```
=> Suppress reporting of ergw_cluster startup process termination

.github/workflows/main.yml, apps/ergw/src/ergw_config.erl, apps/ergw_core/src/ergw_core.app.src, apps/ergw_core/src/ergw_gsn_lib.erl, apps/ergw_core/src/ergw_pfcp_context.erl, apps/ergw_core/test/pfcp_context_SUITE.erl, apps/ergw_core/test/pgw_SUITE.erl, docker/Dockerfile, rebar.config, rebar.lock
This feature should be treated as experimental even when merged.
The preconfigure Tariff-Time in charging profile now has a location
attribute. That location attribute is use to interpret the time a
local time and translate it to UTC for use as a Monitoring Time
in PFCP.
As location name all names from the olsen timezone database are
valid. To specify a UTC time use "Etc/UTC" as location.
This requires also a change to "Tariff-Time" declaration in the config. In the JSON config, it now needs to be something like:
```
"Tariff-Time" : {
"Local-Tariff-Time": "00:00",
"Location": "Europe/Berlin"
}
```
=> add experimental location dependent calculation to Tariff-Time-Change

apps/ergw_core/src/ggsn_gn.erl, apps/ergw_core/src/gtp_context.erl, apps/ergw_core/src/pgw_s5s8.erl, apps/ergw_core/src/saegw_s11.erl, apps/ergw_core/test/ggsn_SUITE.erl, apps/ergw_core/test/pgw_SUITE.erl, apps/ergw_core/test/saegw_s11_SUITE.erl
Rework the context inactivity handling to generate a delete GTP
message with a related cause (PDP address inactivity timer expire /
PDN connection inactivity timer expire).
=> rework context teardown on inactivity to include a proper cause

apps/ergw_core/src/gtp_context.erl
User-Location-Information is optional, so we need to prepared to
handle session without it.
=> fix collect_charging_events when no ULI is present

src/gtp_path.erl, src/pgw_s5s8_proxy.erl
redo of #432
* split the actual fix and debug logging into seperate commits
* only collect debug metadata when needed
=> redo of #432

apps/ergw_core/src/ergw_inet_res.erl, apps/ergw_core/test/node_selection_SUITE.erl, docker/dns-test-server/dns_data/db.test-net-001
The normalize service field is supposed to be ordset. The
normalization instead produced an unsort list. The datatype
itself is the same (a list), but the set operations will not
work as expected on the unsorted list.
=> fix service normalization in NAPTR records from DNS
