- src/pgw_s5s8.erl
- test/ergw_pgw_test_lib.erl
- test/pgw_SUITE.erl
Instead of checking for an actual IP or TEID change, take the pure
presens of the FQ-TEID element as SGW change indication.
3GPP TS 29.274, Sect. 7.2.7 Modify Bearer Request says that we should
consider the content as well, but in practice that is not stable enough
in the presense of middle boxes between the SGW and the PGW
Add test to validate that all required answer element are present on
SGW change.
> change Modify Bearer Request SGW change detection for RAU/TAU/HO

- .travis.yml
Uploading many file to S3 is unbelivable slow. Upload
a single archive instead.
> pack CT logs in to archive and only upload that to S3

- NEWS.md
Also add missed changes for 1.18.2
> Release 1.18.3

- src/ergw_context.erl
- src/ergw_sx_node.erl
- test/ergw_test_sx_up.erl
- test/pgw_SUITE.erl
Small updates for edge cases and test case. No impact on existing behaviors.
> improve UPF restart handling and add tests

- src/ergw_gsn_lib.erl
- src/ergw_gtp_c_socket.erl
- src/gtp_config.erl
- src/pgw_s5s8.erl
- src/pgw_s5s8_proxy.erl
- test/ergw_ggsn_test_lib.erl
- test/ergw_pgw_test_lib.erl
- test/ergw_test_lib.erl
- test/ergw_test_sx_up.erl
- test/ggsn_SUITE.erl
- test/ggsn_proxy_SUITE.erl
- test/pgw_SUITE.erl
- test/pgw_proxy_SUITE.erl
- test/saegw_s11_SUITE.erl
Fix sequence number in triggered GTPv2 requests
> Updates for master 2019 04 15

- src/ergw_gtp_c_socket.erl
- test/ggsn_SUITE.erl
Make it possible to see accepted/rejected session create request
by adding response cause in metrics.
> Tag create session metrics with response cause

- src/ergw_sx_node.erl
- src/ergw_sx_socket.erl
- src/gtp_context.erl
Log exceptions in gtp_context message/request handler but do no ignore
them.
> raise exception in gtp_context request and let the server deal with them

- rebar.config
- rebar.lock
- src/ergw_api.erl
- test/bench_SUITE.erl
- test/ergw_pgw_test_lib.erl
- test/ergw_test_lib.erl
- test/ergw_test_sx_up.erl
* bump ergw AAA for more agressive memory cleanup
* gtp benchmark suite
* mem info cli support `ergw_api:memory(50)`
> gtp benchmark and memory CLI

- src/ergw_api.erl
- src/ggsn_gn.erl
- src/ggsn_gn_proxy.erl
- src/gtp_context.erl
- src/pgw_s5s8.erl
- src/pgw_s5s8_proxy.erl
- src/saegw_s11.erl
change ergw_api:delete_context/1 to not block and choose random contexts
> Fix drain API

- src/ggsn_gn.erl
- src/ggsn_gn_proxy.erl
- src/gtp_api.erl
- src/gtp_context.erl
- src/pgw_s5s8.erl
- src/pgw_s5s8_proxy.erl
- src/saegw_s11.erl
- src/tdf.erl
- test/ergw_test_lib.erl
- test/ggsn_SUITE.erl
- test/ggsn_proxy_SUITE.erl
- test/pgw_SUITE.erl
- test/pgw_proxy_SUITE.erl
- test/saegw_s11_SUITE.erl
- test/tdf_SUITE.erl
use stateful (gen_statem) process for handling contexts.
> stateful context handlers

- METRICS.md
- src/ergw_gtp_c_socket.erl
- src/ergw_prometheus.erl
- src/ergw_sx_node.erl
- src/ergw_sx_socket.erl
- test/ergw_test_lib.erl
- test/ergw_test_sx_up.erl
- test/pgw_SUITE.erl
Move recording and conversion into the same place, thus avoiding any
further inconsitencies.
> fix ms / µs confusion in metrics

- src/ggsn_gn.erl
- src/pgw_s5s8.erl
Should work with the corresponding ergw_aaa changes that add the AVPs to the AAR
> Add allocated pools to session before authorization

- src/ergw_proxy_lib.erl
- src/ergw_sx_node.erl
- test/pgw_proxy_SUITE.erl
> fix late DNS a record lookup

- src/ergw_api.erl
- src/gtp_path.erl
this is alternate version of #192 
Before merging all the commits need to squashed.
> Refactor: move gtp path to gen_statem

- NEWS.md
> News.md updated for 2.5.0

- test/ggsn_proxy_SUITE.erl
- test/pgw_proxy_SUITE.erl
* fix init of counters
* 6 tries is not enough to reliably hit both lb targets
> CT: fix faiure in lb test cases

- rebar.lock
- src/ergw.erl
- src/ergw_config.erl
- src/ergw_gtp_c_socket.erl
- src/ergw_gtp_socket.erl
- src/ergw_gtp_u_socket.erl
- src/ergw_proxy_lib.erl
- src/ergw_socket.erl
- src/ergw_socket_reg.erl
- src/ergw_socket_sup.erl
- src/ergw_sup.erl
- src/ergw_sx_socket.erl
- test/bench_SUITE.erl
- test/config_SUITE.erl
- test/ergw_http_api_SUITE.erl
- test/ggsn_SUITE.erl
- test/ggsn_proxy_SUITE.erl
- test/pgw_SUITE.erl
- test/pgw_proxy_SUITE.erl
- test/saegw_s11_SUITE.erl
- test/sbi_nbsf_SUITE.erl
- test/tdf_SUITE.erl
GTP and Sx sockets (and soon DHCP) are very similar from the config, registry and supervisor handling. Unify them into a common structures.
depends on #199
> unify socket definition and handling

- src/gtp_v1_c.erl
- src/gtp_v1_u.erl
- src/gtp_v2_c.erl
Remove `gtp_msg_types/0` function which is not used in the project
> Remove unused function

- src/ergw_proxy_lib.erl
- src/ggsn_gn_proxy.erl
- src/pgw_s5s8_proxy.erl
- test/ggsn_proxy_SUITE.erl
- test/pgw_proxy_SUITE.erl
Previous closed PR https://github.com/travelping/ergw/pull/220 with discussion.
> Add delete_context/1 for proxy

- NEWS.md
- config/ergw-c-node.config
- rebar.config
- rebar.lock
This PR prepares the changes required for **ergw**:2.6.0
> Release 2.6.0

- test/ggsn_proxy_SUITE.erl
- test/pgw_proxy_SUITE.erl
Invoking meck:unload from the test case itself bears the risk of
not executing it when the test case failes.
> move all meck handling into init/end_per_testcase

- config/ergw-c-node.config
Remove non valid options and fix syntax issue
> Fix broken ergw-c-node.config

- rebar.config
- src/ergw.app.src
Added [SemVer](https://semver.org/) for `erGw` for skip step of change `rebar.config` each time when version of project will update.
> Added semver

- README.md
- config/ergw-c-node.config
- priv/dev.config
- src/ergw_config.erl
- src/ergw_sx_node.erl
- src/ergw_sx_socket.erl
- test/config_SUITE.erl
> Configurable retry timings for SMF / UPF heartbeats

- METRICS.md
- src/ergw_prometheus_collector.erl
- src/ergw_sx_node_reg.erl
- test/ggsn_SUITE.erl
Added Sx association and session counters
> Added PFCP Sx association metric

- rebar.config
- rebar.lock
Update dependencies ergw_aaa to 3.6.10
> Update dependencies ergw_aaa

- apps/ergw_core/src/pgw_s5s8.erl
- apps/ergw_core/src/saegw_s11.erl
delay PFCP action till the Update Beares Response is known
fixes #346
> fix PFCP control during HSS Initiated Subscribed QoS Modification

- apps/ergw_core/src/ergw_inet_res.erl
- apps/ergw_core/test/node_selection_SUITE.erl
this is stacked on top of #354
> DNS: add negative caching for empty responses

- apps/ergw_core/src/gtp_context.erl
Changed 'normal' termination reason to expected 'cp_inactivity_timeout'
> Change 'normal' termination reason

- apps/ergw_core/src/ergw_sx_socket.erl
Let the normal request retry handle send buffer overflow
situations.
> handle timeout in PFCP send

- apps/ergw_core/test/property_test/3gpp_qos_prop.erl
fix compiler warnings in property test
> fix property test

- apps/ergw/src/ergw_compat.erl
- apps/ergw/src/ergw_config.erl
- apps/ergw/test/sbi_nbsf_SUITE_data/ipv4.json
- apps/ergw/test/sbi_nbsf_SUITE_data/ipv6.json
- apps/ergw_core/test/ergw_test_lib.erl
- apps/ergw_core/test/ggsn_SUITE.erl
- apps/ergw_core/test/ggsn_proxy_SUITE.erl
- apps/ergw_core/test/pgw_SUITE.erl
- apps/ergw_core/test/pgw_dist_SUITE.erl
- apps/ergw_core/test/pgw_proxy_SUITE.erl
- apps/ergw_core/test/saegw_s11_SUITE.erl
- apps/ergw_core/test/tdf_SUITE.erl
- rebar.lock
depends on https://github.com/travelping/ergw_aaa/pull/157 , needs rebar.lock update after that PR has been merged.
> update AAA config

- docker/Dockerfile
* [Alpine 3.14.0](https://www.alpinelinux.org/posts/Alpine-3.14.0-released.html)
* [Release Notes](https://wiki.alpinelinux.org/wiki/Release_Notes_for_Alpine_3.14.0)
> Update alpine to 3.14 for Dockerfile

- apps/ergw/src/ergw_config.erl
- apps/ergw/test/smc_SUITE.erl
- apps/ergw/test/smc_SUITE_data/pgw.json
> CONFIG: fix Redirect-Information AVP translation

- apps/ergw_core/src/ergw_pfcp_context.erl
After finding a UPF node that has the required pool, we still need
to trim down the list of available pools to the one that is actually
permited by the APN config.
> fix APN IP pools filter when selecting a pool
